export const ACTION_TYPES = {
  SET_FETCHING_ALL_PRODUCTS: 'SET_FETCHING_ALL_PRODUCTS',
  SET_FETCHING_ALL_PRODUCTS_SUCCESS: 'SET_FETCHING_ALL_PRODUCTS_SUCCESS',
  SET_FETCHING_ALL_PRODUCTS_ERROR: 'SET_FETCHING_ALL_PRODUCTS_ERROR',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_PRODUCT_DETAILS_BY_ID: 'GET_PRODUCT_DETAILS_BY_ID',
  SET_FETCHING_PRODUCT_DETAILS_BY_ID: 'SET_FETCHING_PRODUCT_DETAILS_BY_ID',
  SET_FETCHING_PRODUCT_DETAILS_BY_ID_SUCCESS:
    'SET_FETCHING_PRODUCT_DETAILS_BY_ID_SUCCESS',
  SET_FETCHING_PRODUCT_DETAILS_BY_ID_ERROR:
    'SET_FETCHING_PRODUCT_DETAILS_BY_ID_ERROR',
  // cart items
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  INCREASE_ITEM_QUANTITY: 'INCREASE_ITEM_QUANTITY',
  DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  // toggle favorite
  TOGGLE_FAV_ITEM: 'TOGGLE_FAV_ITEM',
};
