export const ACTION_TYPES = {
  SET_FETCHING_ALL_PRODUCTS: 'SET_FETCHING_ALL_PRODUCTS',
  SET_FETCHING_ALL_PRODUCTS_SUCCESS: 'SET_FETCHING_ALL_PRODUCTS_SUCCESS',
  SET_FETCHING_ALL_PRODUCTS_ERROR: 'SET_FETCHING_ALL_PRODUCTS_ERROR',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
  GET_PRODUCT_DETAILS_SUCCESS: 'GET_PRODUCT_DETAILS_SUCCESS',
};
